### ISSUE TITLE
Large git history file

### ISSUE THREAD

**Issue by esclapez** [infretis/infretis#104]
Some undesirable files may have been commited at some point, making the repository >100MB. It might be worth removing them from the history to lighten the repository (if those are only run results and such).

**Comment by dz24** [comment]
This has now been done, with current repo size of ~3.8 MB.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#using-git-filter-repo

I used this method. NB, the last line, "git push origin --force --tags", was also needed to make things work.
