### ISSUE TITLE
Possibility to combine separate infretis run

### ISSUE THREAD

**Issue by hhlim12** [infretis/infretis#126]
Dear developer, 

Is it possible to combine separate run of infretis, let's say the one run with different initial trajectories, or with different random number..I'd like to try wham analysis including the old trajectories I obtained before.

**Comment by lukasbaldauf** [comment]
That's a good question. We face the same problem during the initialization procedure, where we modify the interface locations on the fly.

I would think that **if the interfaces are the same**, one could append one of the infretis_data.txt files to the other infretis_data.txt file, and then increase all path numbers in the latter file with the maximum path number in the first file.

But, as of now, I'm afraid there is no easy way of combining the data when the interfaces are different, right @TitusvE?

**Comment by hhlim12** [comment]
Thank you for the kind reply. In the future, we plan to use infretis intensely in our research, so we look forward for the new features! For now I think I can just repeat the calculations and use the previous result as initial trajectories.
