### ISSUE TITLE
Zero Pcross at a range of interface despite existence of successful/reactive trajectories in load directory

### ISSUE THREAD

**Issue by hhlim12** [infretis/infretis#130]
Dear developers, 

I got the zero value in the `runav_Pcross.txt` when I performed the `inft wham` analysis despite ~4000 infretis step.
I check the generated paths and see that out of 800 trajectories, 100 trajectories are reactive.
So I wonder it is reasonable to get zero Pcross in this case? 
Should I collect more samples? or is there something wrong in my paths?

Here I attach the `sim.log` and `infretis_data.txt` for reference.

[infretis_data.txt](https://github.com/user-attachments/files/18272214/infretis_data.txt)
[sim.log.txt](https://github.com/user-attachments/files/18272215/sim.log.txt)

Thanks so much in advance.

**Comment by dz24** [comment]
Hi,

Likely one of the ensembles have not sampled any paths that cross the next interface. For example, in RETIS/infretis the global crossing probability is written as

$P(\lambda_B|\lambda_A) = \Pi P(\lambda_{i+1}|\lambda_{i}) = P(\lambda_{N}|\lambda_{N-1})\times\cdots\times P(\lambda_{i+1}|\lambda_{i})\times\cdots\times P(\lambda_{1}|\lambda_{0})$ 

where $\lambda_N = \lambda_B$ and $\lambda_0 = \lambda_A$, and the individual conditional probabilities $P(\lambda_{i+1}|\lambda_{i})$ are calculated by the ensembles defined by $\lambda_i$.

If none of the sampled paths in a certain ensemble cross the next interface, then $P(\lambda_{i+1}|\lambda_{i}) = 0$ and hence also $P(\lambda_B|\lambda_A) = 0$. The probability that one of the $P(\lambda_{i+1}|\lambda_{i})$ will stay zero depends on how close the placements of the two neighboring interfaces $\lambda_i$ and $\lambda_{i+1}$. This is why one would like to place interfaces in a way that all of the $P(\lambda_{i+1}|\lambda_{i})$ values have a nice value that is larger than zero.

You can investigate if this is true by using `inft plot_max_op -ensp i`, where none of the points is above the orange line, or `inft plot_ens`.

The data that you generated in this simulation is still useful, I will be working soon on a function that merges data between simulations (with different interfaces)..

BTW, when applying (inf)retis to study any new system, `Pcross.txt` is unknown and we cannot initially use e.g. `inft estimate_interfaces2.` That is why, we usually estimate (guess) initial interface values $\lambda_i$ and run trial infretis simulations until we have enough data for "good" $\lambda_i$ values to use in a production infretis run.

**Comment by hhlim12** [comment]
Thanks for the kind reply.

I got your explanation.
I asked this question because I also observe the following in the `runavg_ploc.txt`. 
As you can see in the snapshot, the `ploc` for second interface is still zero eventhough the next ones are > 0.
I don't think the barrier is located around the second interface, so I suspect something wrong.

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/dda49a8b-34a0-470e-9ee8-868d1d7f9e54" />

The interface placement is obtained from the `inft estimate_interfaces2`, though I increase some interfaces due to high number of workers.

Below is my final interfaces: 
`[-6.0, -5.7, -2.5, -2.45, -2.40, -2.35, -2.3, -2.25, -2.2, -2.15, -2.10, -2.05, -2.0, -1.95, -1.90, -1.85, -1.80, -1.75, -1.70, -1.65, -1.60, -1.55, -1.50, -1.45, -1.30, -1.25, -1.2, -1.15, -1.0,  0.0,  0.5,  1.5,  3.8]`.

I guess it is zero because the huge difference between 2nd and 3rd interfaces (i.e., from -5.7 to -2.5).
I think I will rerun my simulation and put some interfaces around -5.7 and -2.5.

**Comment by dz24** [comment]
> I guess ploc for [2+] is zero because the huge difference between 2nd and 3rd interfaces (i.e., from -5.7 to -2.5).
I think I will rerun my simulation and put some interfaces around -5.7 and -2.5.

I think that would make sense.

Based on an earlier estimate of Pcross [here](https://github.com/infretis/infretis/issues/123#issuecomment-2542833271), there is a decrease in probability between -5.7 and -2.5, which could mean that the probability of (also) crossing -2.5 given that -5.7 is crossed, may not be that high. So more interfaces / moving them closer would be something I would want to do.

**Comment by hhlim12** [comment]
I got it. Thanks very much!

**Comment by dz24** [comment]
@hhlim12 You should now be able to combine results from different infretis simulations (as long as they have the same $\lambda_A$ and $\lambda_B$ by using `inft combine_data` if you update to the latest vesion of [inftools](https://github.com/infretis/inftools) as seen by the following [PR](https://github.com/infretis/inftools/pull/10)

**Comment by hhlim12** [comment]
@dz24 , Thanks very much for the great update!

I confirm that it works without a problem for my files.

**Comment by dz24** [comment]
@hhlim12 @mind-scraper In the case that you are still using `inft combine_data`, I suggest to update the https://github.com/infretis/inftools package, as the error predictions is more accurate in the new version https://github.com/infretis/inftools/pull/13, as explained by https://github.com/infretis/inftools/pull/10#issuecomment-2627645615.

**Comment by mind-scraper** [comment]
Thank you for the update. I will update mine right away 👍

**Comment by hhlim12** [comment]
@dz24 , Thanks for the update. I confirm that the update works fine for me..
