### ISSUE TITLE
gromacs velocity generation

### ISSUE THREAD

**Issue by lukasbaldauf** [infretis/infretis#16]
It seems that the velocity distribution obtained with gromacs using gen-vel is not the boltzmann distribution. Therefore, the distribution of the old shooting point (which is a boltzmann distribution if equilibrated during path sampling) and the generated velocities (using gmx gen-vel) are different, and they do not cancel in the detailed balance relation (flexible length shooting acceptance criteria)?

**Comment by lukasbaldauf** [comment]
Yes, I was referring to the `.mdp` option.

I generated 10,000 random velocities with `gen-temp = 300` and `gen-seed = -1` for a toy system of 2 hydrogen atoms. I expect a Boltzmann distribution of the kinetic energies, which I get from a long thermostatted MD run, but I get this instead:

![histograms](https://github.com/infretis/infretis/assets/74910029/9f5665df-180e-404a-9c18-ae11f1bf8464)

With grompp using `gen-vel = yes` it appears cut off at higher values.

[I found a link for the velocity generation method](https://manual.gromacs.org/documentation/current/reference-manual/algorithms/molecular-dynamics.html#coordinates-and-velocities), where they talk about removing the center-of-mass and rescaling the velocities to match the temperature exactly.

**Comment by andersle** [comment]
Is it bounded because there are only two atoms and the kinetic energy is scaled to match 300 K? I mean, if the kinetic energy is scaled, then $E_{k,1} + E_{k,2} = \text{constant}$ and if $E_{k,1}$ is the smallest it can be (zero) then $E_{k,2} = \text{constant}$ and this is the maximum (its upper bound)?

**Comment by andersle** [comment]
> Is it bounded because there are only two atoms and the kinetic energy is scaled to match 300 K? I mean, if the kinetic energy is scaled, then Ek,1+Ek,2=constant and if Ek,1 is the smallest it can be (zero) then Ek,2=constant and this is the maximum (its upper bound)?

Hmm, according to what I say here, there should be no distribution at all in the graph?

**Comment by lukasbaldauf** [comment]
Yes if they rescale the velocities I would expect a spike in the graph at the kinetic energy corresponding to the given temperature, so I don't actually think it's rescaled.

I also see that when using a larger number of particles, e.g. 20, the distribution approaches that of a Boltzmann distribution.

**Comment by lukasbaldauf** [comment]
> > Is it bounded because there are only two atoms and the kinetic energy is scaled to match 300 K? I mean, if the kinetic energy is scaled, then Ek,1+Ek,2=constant and if Ek,1 is the smallest it can be (zero) then Ek,2=constant and this is the maximum (its upper bound)?
> 
> Hmm, according to what I say here, there should be no distribution at all in the graph?

After inspecting the gromacs source code it turns out that the velocities are indeed scaled to match the temperature exactly, and that the kinetic energy therefore is upper bound, just as you said! The reason there is a distribution is that the momentum is removed after this rescaling. Depending on the relative velocities of the two atoms, we may need to remove a given amount of energy (if the velocities are not exactly opposite) or not. So the energy is upper bound, but it can be less than the upper bound.

Here are the two resulting velocity distributions, which reproduce the kinetic energy, one generated from an equilibrium run and one using `grompp` with gen-vel = True.

![velocities](https://github.com/infretis/infretis/assets/74910029/bc12762a-0010-44aa-a973-a29b0aa64130)

Removing the total momentum does not affect the dynamics, but scaling the velocities to match the temperature does, right? Especially for small systems where temperature fluctuations can be large, but these may only be interesting for test cases. I therefore add the option to generate velocities internally for now.
