### ISSUE TITLE
gromacs engine

### ISSUE THREAD

**Issue by lukasbaldauf** [infretis/infretis#30]
Check that the shooting point coordinates are not modified when shooting and that the order parameter does not change. There are some rounding-off errors when comparing conf.g96 and genvel.g96 that can result in "KOB" for 001 ensembles. This is not checked in higher ensembles.

**Comment by lukasbaldauf** [comment]
In some cases, atoms jump between the periodic boundaries of the box when going from conf.g96 to genvel.g96.

**Comment by sroet** [comment]
> There are some rounding-off errors when comparing conf.g96 and genvel.g96 that can result in "KOB" for 001 ensembles.

If it is using the full 15.9 floats [as it claims](https://manual.gromacs.org/current/reference-manual/file-formats.html#g96) that would mean the jumping is happening on the  `10^{-9} nm = 1 am (atto meter)` scale, which really should not happen, right? (I am assuming `nm` as that is the default GROMACS distance measurement)

**Comment by lukasbaldauf** [comment]
Yea that should be unlikely.

After visualizing some of the configurations it seems that the jumping arises because molecules are made whole when going conf.g96 to genvel.g96.

**Comment by lukasbaldauf** [comment]
The problem was in the order parameter calculation, where a slightly different box size than the simulation box size was used, causing problems when atoms jumped across boundaries.
