### ISSUE TITLE
Path lengths

### ISSUE THREAD

**Issue by lukasbaldauf** [infretis/infretis#61]
In some cases, path lengths are incorrectly set to 10'000 in infretis_data.txt and sim.log, when they are longer (as in order.txt, traj.txt, energy.txt)

**Comment by andersle** [comment]
Is there a reason for path.empty_path() sometimes set the maxlen and sometimes not? Like:

```python
back_segment = source_seg.empty_path(
    maxlen=ens_set["tis_set"]["maxlength"]
)
```

vs `new_segment = path.empty_path()`

**Comment by lukasbaldauf** [comment]
Maybe thats the reason. The new path should obtain the maxlen from the parent path that we empty, but if maxlen is not set in the firsts place because of this, it defaults to 10'000. 

I ran some tests earlier, and it looks like the crossing probability gets affected alot.

**Comment by lukasbaldauf** [comment]
We often use the `dict.get()` method. Maybe we should avoid this because in many cases i see

```python
ens_set.get("maxlength", DEFAULT_MAXLEN)
```
when it should be `ens_set["tis_set"]["maxlength"]`.

**Comment by andersle** [comment]
So it is doing

```python
ens_set.get("maxlength", DEFAULT_MAXLEN)
```

when it should be

```python
ens_set["tis_set"]["maxlength"]
# or:
ens_set["tis_set"].get("maxlength", DEFAULT_MAXLEN)
```
?

We could remove the `.get()` and just make it fail if the settings are not given. This should not be a problem, since default arguments should have been inserted at some point prior to accessing the setting. (Assuming that default arguments are properly inserted!)

**Comment by lukasbaldauf** [comment]
> So it is doing
> 
> ```python
> ens_set.get("maxlength", DEFAULT_MAXLEN)
> ```
> 
> when it should be
> 
> ```python
> ens_set["tis_set"]["maxlength"]
> # or:
> ens_set["tis_set"].get("maxlength", DEFAULT_MAXLEN)
> ```
> 
> ?

Yes exactly
> We could remove the `.get()` and just make it fail if the settings are not given. This should not be a problem, since default arguments should have been inserted at some point prior to accessing the setting. (Assuming that default arguments are properly inserted!)

Yes i think that would be much cleaner!
