### ISSUE TITLE
NVE or NVT dynamics in infretis simulation with LAMMPS

### ISSUE THREAD

**Issue by hhlim12** [infretis/infretis#99]
Dear developers, 

Thanks so much for the development.
I'm very interested in applying this method to my work.

I'd like to ask some questions about the path generated by infretis.
I'm using LAMMPS to propagate the trajectory.

As shown in the example, the LAMMPS input file is specified like this:

```
# variables to be replaced by infretis
variable 	subcycles index infretis_subcycles
variable	timestep index infretis_timestep
variable	nsteps index infretis_nsteps
variable	initconf index infretis_initconf
variable	name index infretis_name
variable 	lammpsdata index infretis_lammpsdata
variable	temperature index infretis_temperature
variable	seed index infretis_seed

units real
atom_style full

dimension 3
boundary p p p

pair_style lj/cut/coul/cut 12.0 12.0
pair_modify mix arithmetic tail yes

read_data ${lammpsdata} # add
read_dump ${initconf} 0 x y z vx vy vz box yes # add

fix 1 all nve
fix 2 all langevin ${temperature} ${temperature} 500.0 ${seed}

thermo ${subcycles}
thermo_style custom step ke pe etotal temp

dump 1 all custom ${subcycles} ${name}.lammpstrj id type x y z vx vy vz # add
dump_modify 1 pbc yes

timestep ${timestep} # add

run ${nsteps} # ad
```

The input shows the temperature is controlled by Langevin thermostat.
However, controlling the temperature makes the path is not time-reversible.

My questions are as follows.
1. Should it be better if I use NVE instead? Then what happen to the temperature we specified in the toml file?
2. Is there a difference between infretis temperature for path sampling and the temperature in the propagating trajectory?

I'd very appreciate if you can give some comments..

**Comment by lukasbaldauf** [comment]
Hi, thank you for the feedback. I’ll try to clarify a bit. 

The temperature specified in the .toml means that, when shooting, we draw random velocities from a Maxwell-Boltzmann distribution at that temperature.

1) You are correct that the dynamics are not reversible with this thermostat. We often use NVE dynamics, which results in NVE with NVT shooting. In that case simply remove the thermostat line from the lammps file. 

2) So by now it’s maybe a bit more clear what the difference between the temperatures is; the infretis temperature is used to draw velocities, while the temperature of the propagation is specified by the thermostat, and they should in  almost all cases be the same.

Btw, the lammps engine hasn’t been tested too much and hasn’t been used for a lot of production runs. So there are a some limitations as of now, such that the units should be set to real and only lammpsdump formats are supported for trajectories. But we are happy to change that if needed. 

Let me know if you have any other questions or need help.

**Comment by hhlim12** [comment]
@lukasbaldauf , thanks so much for the clarifying this!

Currently I'm running infretis with LAMMPS without a problem.
But I just realize that only the units 'real' are supported at the moment.
I actually use other units for my system but I can just correctly convert them to 'real' units.
I might ask some more questions in the future.

Thanks a lot!

**Comment by hhlim12** [comment]
Hi, It turns out that my force-field used 'metal' units. 
So I'm not really sure it is safe to convert my lammps input file to 'real units'. 

Actually, I found that the units of velocity in 'real' and 'metal' don't differ much.
'real' units uses Å/fs while metal uses Å/ps.

<img width="442" alt="image" src="https://github.com/infretis/infretis/assets/77390746/f5aacbd3-784c-488c-843b-31d0a6e50955">


In order to use 'metal' units, I'm thinking modifying the code a little bit (taken from `lammps.py`).
```python
   def modify_velocities(
        self, system: System, vel_settings: dict[str, Any]
    ) -> tuple[float, float]:
        """Modify the velocities of all particles.

        Args:
            system: The system whose particle velocities are to be modified.
            vel_settings: A dict containing
                'zero_momentum': boolean, if true we reset the linear momentum
                  to zero after generating velocities internally.

        Returns:
            A tuple containing:
                - dek: The change in kinetic energy as a result of
                    the velocity modification.
                - kin_new: The new kinetic energy of the system.

        Note:
            This method does **not** take care of constraints.
        """
        mass = self.mass
        beta = 1 / (self.kb * vel_settings["temperature"])
        # energy is in units kcal/mol which we want to convert
        # to units (g/mol)*Å^2/fs (units of m*v^2), the velocity
        # units of lammps.
        # using Unitful:
        #   uconvert((u"kcal/g")^0.5, 1u"Å/fs") = 48.88821290839617
        # so we need to scale the velocities by this factor
        scale = 48.88821290839617
        pos = self.dump_frame(system)
        id_type, xyz, vel, box = read_lammpstrj(pos, 0, self.n_atoms)
        kin_old = kinetic_energy(vel, mass)[0]
        vel, _ = self.draw_maxwellian_velocities(vel, mass, beta)
        # convert to correct units
        vel /= scale # Unit is Å/fs
        vel *= 1000 # Unit is Å/ps
        # reset momentum is not the default in LAMMPS
        if vel_settings.get("zero_momentum", False):
            vel = reset_momentum(vel, mass)

        conf_out = os.path.join(self.exe_dir, f"genvel.{self.ext}")
        write_lammpstrj(conf_out, id_type, xyz, vel, box)
        kin_new = kinetic_energy(vel, mass)[0]
        system.config = (conf_out, 0)
        system.ekin = kin_new
        if kin_old == 0.0:
            dek = float("inf")
            logger.debug(
                "Kinetic energy not found for previous point."
                "\n(This happens when the initial configuration "
                "does not contain energies.)"
            )
        else:
            dek = kin_new - kin_old
        return dek, kin_new
```

In particular, I just put the following:
```python
      # convert to correct units
        vel /= scale # Unit is Å/fs
        vel *= 1000 # Unit is Å/ps
```

Then the unit of velocity is now consistent to 'metal' units which is Å/ps.
Would you mind to confirm this?

**Comment by lukasbaldauf** [comment]
Yes that should correctly take care of everything. 

The Boltzmann constant is in units of kcal/mol, but it doesn’t matter in this case since self.kb and self.beta are only used here. 

This also changes the units of the kinetic energy and the change in kinetic energy “dek”, but I don’t think they are used anywhere useful atm. 

So this looks good to me!

**Comment by mind-scraper** [comment]
Hi, sorry to bring this up again. 
Is there any measure of how wrong our infRETIS calculation will be if we use NVT instead of NVE?

I need to run path sampling at a very high temperature, more than 1000K. Sometimes the temperature fluctuates widely (+/- 300K or even worse). I am worried that the quantity obtained from my infRETIS calculation, like Pcross or reaction rate, does not reflect the true value at the target temperature I am interested in.

**Comment by dz24** [comment]
@TitusvE

**Comment by TitusvE** [comment]
Hi,

I’ve been reading through the full discussion and would like to address a point mentioned earlier:

Langevin dynamics is, in principle, time-reversible, but this depends on how the time-step integrator is implemented. I’m not sure how LAMMPS handles this specifically, but there are integrators like BOAOB that preserve time-reversibility.

The reason we often prefer NVE (deterministic dynamics) combined with NVT shooting is that thermostats artificially tweak the dynamics. While this is perfectly fine for obtaining thermodynamic properties, if you aim to simulate the dynamics of a process as accurately as possible, there are valid arguments against using thermostat-controlled dynamics. Thermostats can distort the natural dynamics.

There are, however, cases where thermostats are appropriate for dynamic simulations. For example, when modeling an implicit solvent while explicitly simulating solute molecules, the Langevin stochastic random force can represent collisions with implicit solvent molecules. In such cases, the friction coefficient can be tuned to mimic experimental conditions. On the other hand, for fully atomistic models, a Langevin thermostat introduces a non-physical disturbance to the true dynamics.

While this disturbance is generally not a significant issue (given other artifacts like periodic boundary conditions, imperfect force fields, etc.), it becomes relevant when fluctuations in kinetic energy influence rare events. For example, consider a chain reaction where the heat released from one reaction step triggers the next reaction step. If the thermostat is coupled too strongly, it could suppress temporary kinetic energy fluctuations, thereby inhibiting subsequent reaction steps.

This explains why the average temperature might appear “wrong” for a RETIS simulation that uses NVE dynamics if you calculate averages based on the kinetic energy of all paths. In fact, this deviation is physically correct in this context (See, for example, “Transition paths are hot,” https://iopscience.iop.org/article/10.1209/0295-5075/113/18004).

However, if you calculate the temperature averages only for the [0+] and [0-] ensembles, you are likely to obtain the correct temperature by averaging out the kinetic energy.

**Comment by mind-scraper** [comment]
Thank you very much for the clear explanation. 

I have confirmed that by using NVE, the temperature in the [0+] and [0-] ensembles (000 interface?) is the same as the simulation temperature while it is not for other interfaces. 

The data shown below is obtained from the average of 5000 trajectories of each interface. 

```
#Simluation temperature = 1000K
#Interface | Temperature (K)
[000] | 1003.2296220325868
[010] | 984.0080760320955
[020] | 980.2028019319016
[030] | 981.5585770484934
[043] | 987.1557338230369

```

**Comment by TitusvE** [comment]
Yes, 000 and 001 refer to the [0-] and [0+] ensemble, respectively. 002 to the [1+] ensemble etc
